mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.zze0.demo.shardingjdbc.entity

spring:
  shardingsphere:
    props:
      sql:
        show: true
    datasource:
      names: master0, master0slave0, master1, master1slave0
      master0:
        driver-class-name: com.mysql.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://127.0.0.1:3306/zze0_demo?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&autoReconnect=true&failOverReadOnly=false
        username: a
        password: a
      master0slave0:
        driver-class-name: com.mysql.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://127.0.0.1:3306/zze0_demo?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&autoReconnect=true&failOverReadOnly=false
        username: a
        password: a
      master1:
        driver-class-name: com.mysql.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://127.0.0.1:3306/zze0_demo_1?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&autoReconnect=true&failOverReadOnly=false
        username: a
        password: a
      master1slave0:
        driver-class-name: com.mysql.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://127.0.0.1:3306/zze0_demo_1?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&autoReconnect=true&failOverReadOnly=false
        username: a
        password: a
    sharding:
      default-data-source-name: ds0
      default-database-strategy:
        hint:
          algorithm-class-name: com.zze0.demo.shardingjdbc.sharding.ModuloHintShardingAlgorithm
      master-slave-rules:
        ds0:
          master-data-source-name: master0
          slave-data-source-names: master0slave0
        ds1:
          master-data-source-name: master1
          slave-data-source-names: master1slave0
      tables:
        _user:
          actual-data-nodes: ds$->{0..1}._user
